# Battery Monitoring ETL Project

End-to-end ETL pipeline using Python, PostgreSQL, SQL and Power BI.

## Import Libraries

In [1]:
import psycopg2

print("psycopg2 installed")

psycopg2 installed

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

password = quote_plus("Prashant@123")

engine = create_engine(
    f"postgresql+psycopg2://postgres:{password}@localhost:5432/battery_monitoring"
)
print("Engine Created")

Engine Created

In [4]:
import pandas as pd

query = """
SELECT *
FROM battery_data
"""

df = pd.read_sql(query, engine)

print(df.shape)

df.head()

(11, 10)

,recordid,batteryid,batteryname,voltage,current,temperature,location,readingtime,batterystatus,dataquality
0,1,1,Battery-A,542.0,24.0,31.0,Mumbai,2026-06-01 10:00:00,Good,COMPLETE DATA
1,2,2,Battery-B,535.0,22.0,29.0,Pune,2026-06-01 10:00:00,Warning,COMPLETE DATA
2,3,3,Battery-C,NaN,25.0,33.0,Navi Mumbai,2026-06-01 10:00:00,No Voltage,INCOMPLETE DATA
3,4,4,Battery-D,518.0,21.0,35.0,Mumbai,2026-06-01 10:00:00,Critical,COMPLETE DATA
4,5,5,Battery-E,550.0,26.0,NaN,Pune,2026-06-01 10:00:00,Good,INCOMPLETE DATA

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   recordid       11 non-null     int64
 1   batteryid      11 non-null     int64
 2   batteryname    11 non-null     str
 3   voltage        10 non-null     float64
 4   current        10 non-null     float64
 5   temperature    10 non-null     float64
 6   location       11 non-null     str
 7   readingtime    11 non-null     datetime64[us]
 8   batterystatus  11 non-null     str
 9   dataquality    11 non-null     str
dtypes: datetime64[us](1), float64(3), int64(2), str(4)
memory usage: 1.4 KB

In [6]:
df.isnull().sum()

recordid         0
batteryid        0
batteryname      0
voltage          1
current          1
temperature      1
location         0
readingtime      0
batterystatus    0
dataquality      0
dtype: int64

In [7]:
df.describe()

,recordid,batteryid,voltage,current,temperature,readingtime
count,11.000000,11.000000,10.000000,10.000000,10.000000,11
mean,6.000000,6.000000,537.700000,23.700000,31.700000,2026-06-04 01:56:53.523369
min,1.000000,1.000000,499.000000,18.000000,28.000000,2026-06-01 10:00:00
25%,3.500000,3.500000,531.250000,22.250000,29.250000,2026-06-01 10:00:00
50%,6.000000,6.000000,543.500000,24.500000,30.500000,2026-06-01 10:00:00
75%,8.500000,8.500000,549.500000,25.750000,32.750000,2026-06-01 10:00:00
max,11.000000,11.000000,560.000000,27.000000,40.000000,2026-06-30 17:25:48.757061
std,3.316625,3.316625,18.043466,2.750757,3.591657,NaN

In [8]:
df.groupby('location')['voltage'].mean()

location
Mumbai         539.6
Navi Mumbai    499.0
Pune           545.0
Name: voltage, dtype: float64

In [9]:
df.groupby('location').agg({
    'batteryid': 'count',
    'voltage': ['count', 'mean']
})

            batteryid voltage
                count   count   mean
location
Mumbai              5       5  539.6
Navi Mumbai         2       1  499.0
Pune                4       4  545.0

In [10]:
df[df.isnull().any(axis=1)]

,recordid,batteryid,batteryname,voltage,current,temperature,location,readingtime,batterystatus,dataquality
2,3,3,Battery-C,NaN,25.0,33.0,Navi Mumbai,2026-06-01 10:00:00,No Voltage,INCOMPLETE DATA
4,5,5,Battery-E,550.0,26.0,NaN,Pune,2026-06-01 10:00:00,Good,INCOMPLETE DATA
8,9,9,Battery-I,545.0,NaN,32.0,Pune,2026-06-01 10:00:00,Good,INCOMPLETE DATA

Battery-C
Voltage = Missing

Battery Status calculate nahi kar sakte
Average Voltage affect hoga

Battery-E
Temperature = Missing

Battery heat analysis nahi kar sakte
Voltage analysis kar sakte

Battery-I
Current = Missing

Current analysis nahi kar sakte
Voltage analysis kar sakte

In [11]:
df['voltage'].mean()

np.float64(537.7)

In [12]:
df['voltage'] = df['voltage'].fillna(
    df['voltage'].mean()
)

df['voltage']

0     542.0
1     535.0
2     537.7
3     518.0
4     550.0
5     550.0
6     499.0
7     560.0
8     545.0
9     530.0
10    548.0
Name: voltage, dtype: float64

In [13]:
df[df['batteryname'] == 'Battery-C']

,recordid,batteryid,batteryname,voltage,current,temperature,location,readingtime,batterystatus,dataquality
2,3,3,Battery-C,537.7,25.0,33.0,Navi Mumbai,2026-06-01 10:00:00,No Voltage,INCOMPLETE DATA

In [14]:
df['current'].mean()

np.float64(23.7)

In [15]:
df['temperature'].mean()

np.float64(31.7)

In [16]:
df['current'] = df['current'].fillna(
    df['current'].mean()
)

df['temperature'] = df['temperature'].fillna(
    df['temperature'].mean()
)

In [17]:
df.isnull().sum()

recordid         0
batteryid        0
batteryname      0
voltage          0
current          0
temperature      0
location         0
readingtime      0
batterystatus    0
dataquality      0
dtype: int64

In [18]:
df.head()

,recordid,batteryid,batteryname,voltage,current,temperature,location,readingtime,batterystatus,dataquality
0,1,1,Battery-A,542.0,24.0,31.0,Mumbai,2026-06-01 10:00:00,Good,COMPLETE DATA
1,2,2,Battery-B,535.0,22.0,29.0,Pune,2026-06-01 10:00:00,Warning,COMPLETE DATA
2,3,3,Battery-C,537.7,25.0,33.0,Navi Mumbai,2026-06-01 10:00:00,No Voltage,INCOMPLETE DATA
3,4,4,Battery-D,518.0,21.0,35.0,Mumbai,2026-06-01 10:00:00,Critical,COMPLETE DATA
4,5,5,Battery-E,550.0,26.0,31.7,Pune,2026-06-01 10:00:00,Good,INCOMPLETE DATA

In [19]:
def get_status(voltage):

    if voltage > 540:
        return "Good"

    elif voltage >= 520:
        return "Warning"

    else:
        return "Critical"

In [20]:
df['New_BatteryStatus'] = df['voltage'].apply(get_status)

In [21]:
df[['batteryname','voltage','batterystatus','New_BatteryStatus']]

   batteryname  voltage batterystatus New_BatteryStatus
0    Battery-A    542.0          Good              Good
1    Battery-B    535.0       Warning           Warning
2    Battery-C    537.7    No Voltage           Warning
3    Battery-D    518.0      Critical          Critical
4    Battery-E    550.0          Good              Good
5    Battery-F    550.0          Good              Good
6    Battery-G    499.0      Critical          Critical
7    Battery-H    560.0          Good              Good
8    Battery-I    545.0          Good              Good
9    Battery-J    530.0       Warning           Warning
10   Battery-K    548.0          Good              Good

In [22]:
df['New_BatteryStatus'].value_counts()

New_BatteryStatus
Good        6
Warning     3
Critical    2
Name: count, dtype: int64

In [23]:
df['batterystatus'] = df['New_BatteryStatus']

In [24]:
df.drop(columns=['New_BatteryStatus'], inplace=True)

In [26]:
df.drop(columns=['current'], inplace=True)

In [ ]:
df.head()

,recordid,batteryid,batteryname,voltage,current,temperature,location,readingtime,batterystatus,dataquality
0,1,1,Battery-A,542.000000,24.0,31.000000,Mumbai,2026-06-01 10:00:00,Good,COMPLETE DATA
1,2,2,Battery-B,535.000000,22.0,29.000000,Pune,2026-06-01 10:00:00,Warning,COMPLETE DATA
2,3,3,Battery-C,536.555556,25.0,33.000000,Navi Mumbai,2026-06-01 10:00:00,Warning,INCOMPLETE DATA
3,4,4,Battery-D,518.000000,21.0,35.000000,Mumbai,2026-06-01 10:00:00,Critical,COMPLETE DATA
4,5,5,Battery-E,550.000000,26.0,31.888889,Pune,2026-06-01 10:00:00,Good,INCOMPLETE DATA

In [ ]:
df.columns

Index(['recordid', 'batteryid', 'batteryname', 'voltage', 'current',
       'temperature', 'location', 'readingtime', 'batterystatus',
       'dataquality'],
      dtype='object')

In [ ]:
df.to_csv(
    "battery_cleaned.csv",
    index=False
)

print("File Saved")

File Saved

In [ ]:
import os

os.getcwd()

'c:\\Users\\DELL\\Desktop\\Vendor Performance DA'

In [ ]:
df.head()

,recordid,batteryid,batteryname,voltage,current,temperature,location,readingtime,batterystatus,dataquality
0,1,1,Battery-A,542.0,24.0,31.0,Mumbai,2026-06-01 10:00:00,Good,COMPLETE DATA
1,2,2,Battery-B,535.0,22.0,29.0,Pune,2026-06-01 10:00:00,Warning,COMPLETE DATA
2,3,3,Battery-C,537.7,25.0,33.0,Navi Mumbai,2026-06-01 10:00:00,Warning,INCOMPLETE DATA
3,4,4,Battery-D,518.0,21.0,35.0,Mumbai,2026-06-01 10:00:00,Critical,COMPLETE DATA
4,5,5,Battery-E,550.0,26.0,31.7,Pune,2026-06-01 10:00:00,Good,INCOMPLETE DATA

In [ ]:
df.to_sql(
    "battery_cleaned_data",
    engine,
    if_exists="replace",
    index=False
)

print("Data uploaded successfully!")

Data uploaded successfully!

In [ ]:
df[df["batteryname"] == "Battery-C"]

,recordid,batteryid,batteryname,voltage,current,temperature,location,readingtime,batterystatus,dataquality
2,3,3,Battery-C,537.7,25.0,33.0,Navi Mumbai,2026-06-01 10:00:00,Warning,INCOMPLETE DATA

In [ ]:
print(df.shape)

(11, 10)

In [ ]:
df.tail()

,recordid,batteryid,batteryname,voltage,current,temperature,location,readingtime,batterystatus,dataquality
6,7,7,Battery-G,499.0,18.0,40.0,Navi Mumbai,2026-06-01 10:00:00.000000,Critical,COMPLETE DATA
7,8,8,Battery-H,560.0,27.0,28.0,Mumbai,2026-06-01 10:00:00.000000,Good,COMPLETE DATA
8,9,9,Battery-I,545.0,23.7,32.0,Pune,2026-06-01 10:00:00.000000,Good,INCOMPLETE DATA
9,10,10,Battery-J,530.0,23.0,29.0,Mumbai,2026-06-01 10:00:00.000000,Warning,COMPLETE DATA
10,11,11,Battery-K,548.0,25.0,30.0,Mumbai,2026-06-30 17:25:48.757061,Good,COMPLETE DATA